version: "3.9"
services:
  pos:
    build: .
    container_name: unitill-pos
    env_file: 
      - pos.env.dev
    ports:
      - "8080:8080"
    volumes:
      - pos_data:/app/data
      # - /Users/farshid/repos/unitill/images:/samples:ro
    restart: unless-stopped
volumes:
  pos_data:
