package pages

import (
	"net/http"
	"strings"
	"testing"
)

// The manual's screenshots (generated by `make docs-shots` into
// web/help/img/<locale>/<id>.png, embedded via web.HelpFS) are served by
// GET /help/img/{locale}/{file}. en/sell.png is guaranteed to exist —
// guard-docs-shots.sh fails CI when any routed topic's screenshot is missing.
func TestHelpImgServesEmbeddedScreenshot(t *testing.T) {
	rec := get(t, helpMux(t), "/help/img/en/sell.png")
	if rec.Code != http.StatusOK {
		t.Fatalf("GET /help/img/en/sell.png: %d", rec.Code)
	}
	if ct := rec.Header().Get("Content-Type"); ct != "image/png" {
		t.Errorf("content-type = %q, want image/png", ct)
	}
	if rec.Body.Len() == 0 {
		t.Error("empty body for an existing screenshot")
	}
}

// A missing screenshot is a clean 404 — no broken half-response.
func TestHelpImgMissingIs404(t *testing.T) {
	mux := helpMux(t)
	for _, p := range []string{
		"/help/img/en/no-such-topic.png",
		"/help/img/xx/sell.png", // locale with no screenshots
		"/help/img/en/sell.txt", // only .png is ever generated or served
	} {
		if rec := get(t, mux, p); rec.Code != http.StatusNotFound {
			t.Errorf("%s: %d, want 404", p, rec.Code)
		}
	}
}

// The path params must never walk the filesystem — same rule as manual.Topic's
// id check. Encoded dots/slashes decode into the PathValue, so the handler has
// to reject them itself.
func TestHelpImgTraversalRejected(t *testing.T) {
	mux := helpMux(t)
	for _, p := range []string{
		"/help/img/en/%2e%2e%2f%2e%2e%2flocales%2fen.json",
		"/help/img/%2e%2e/en/sell.png",
		"/help/img/en/..%2fsell.png",
		// This one is what actually distinguishes "the guard rejected it"
		// from "it 404'd for an unrelated reason": every case above resolves
		// to a path that doesn't exist even without the guard. This one
		// walks right back to a real file — en/sell.png exists — so
		// path.Join's own cleaning would happily serve it were the
		// ContainsAny/Contains checks removed (confirmed locally by
		// temporarily deleting them: this one 200s with a real PNG body,
		// the others still 404 on their own).
		"/help/img/en/%2e%2e%2fen%2fsell.png",
	} {
		rec := get(t, mux, p)
		if rec.Code == http.StatusOK {
			t.Errorf("%s: served (200) — traversal not rejected", p)
		}
		if body := rec.Body.String(); strings.Contains(body, "{") && strings.Contains(body, "\"") {
			// Crude but sufficient: a JSON locale file leaking out would
			// look like this; a 404 page never does.
			t.Errorf("%s: response looks like leaked file content: %q", p, body[:min(len(body), 80)])
		}
	}
}

// The topic page itself carries the screenshot markup once one exists for the
// serving locale — the manual package injects it at load time.
func TestHelpTopicPageIncludesScreenshot(t *testing.T) {
	rec := get(t, helpMux(t), "/help/sell")
	if rec.Code != http.StatusOK {
		t.Fatalf("GET /help/sell: %d", rec.Code)
	}
	if !strings.Contains(rec.Body.String(), `<img src="/help/img/en/sell.png"`) {
		t.Error("topic page missing its screenshot")
	}
}
