// Shared plumbing for the manual's screenshot harness (`make docs-shots`):
// which topics get a screenshot, and the freshness hashes recorded in
// web/help/img/manifest.json.
//
// CommonJS on purpose — required both by docs-shots.spec.ts (Playwright
// transpiles specs to CJS) and by the plain-node write-manifest.js entry.
//
// HASH ALGORITHM — must stay in lockstep with scripts/ci/guard-docs-shots.sh
// (the CI side recomputes the same values in python3):
//
//   sha256 of a file      = lowercase hex sha256 of its raw bytes.
//   surface fileset       = every regular file under web/ui/ (recursive)
//                           PLUS every regular file under web/public/
//                           (recursive) — the CSS/JS that actually paints
//                           the templates, e.g. app.css's statusbar colors,
//                           which docs-shots.spec.ts's mask relies on
//                           PLUS every *.go under internal/pages/ (recursive)
//                           excluding *_test.go — the app surface that could
//                           change what a screenshot shows.
//                           web/locales/**/*.json is deliberately excluded —
//                           see the matching note in guard-docs-shots.sh.
//   surface_sha256        = sha256 of the UTF-8 concatenation of one line per
//                           fileset file, sorted lexicographically by its
//                           repo-relative POSIX path (paths are ASCII, so JS
//                           and python sort identically):
//                               "<sha256(file)>  <relpath>\n"
//                           (two spaces — the sha256sum output format).
//   topic hash            = sha256 of web/help/<locale>/<id>.md, falling back
//                           to web/help/en/<id>.md when the locale has no
//                           translation (mirroring manual.FallbackLocale).
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const repoRoot = path.resolve(__dirname, '..', '..');

// The locales the till ships its manual in (web/help/<locale>/).
const LOCALES = ['en', 'fa', 'ar', 'tr'];

function sha256Hex(buf) {
  return crypto.createHash('sha256').update(buf).digest('hex');
}

// routedTopics parses the same tiny front-matter subset internal/manual's
// parseTopic does ("key: value", "key: [a, b]") — keep in sync with it — and
// returns only the topics that declare a routes: field, each with its FIRST
// route (the screenshot target). Route-less topics get no screenshot (a
// follow-up backlog card covers them).
function routedTopics() {
  const dir = path.join(repoRoot, 'web', 'help', 'en');
  const out = [];
  for (const name of fs.readdirSync(dir).filter((n) => n.endsWith('.md')).sort()) {
    const text = fs.readFileSync(path.join(dir, name), 'utf8').replace(/\r\n/g, '\n');
    if (!text.startsWith('---\n')) continue;
    const end = text.indexOf('\n---', 4);
    if (end < 0) continue;
    let id = null;
    let routes = null;
    for (const rawLine of text.slice(4, end).split('\n')) {
      const m = /^([A-Za-z_]+):\s*(.*)$/.exec(rawLine.trim());
      if (!m) continue;
      if (m[1] === 'id') id = m[2].trim();
      if (m[1] === 'routes') {
        routes = m[2]
          .replace(/^\[/, '')
          .replace(/\]$/, '')
          .split(',')
          .map((s) => s.trim().replace(/^["']|["']$/g, ''))
          .filter(Boolean);
      }
    }
    if (id && routes && routes.length > 0) out.push({ id, route: routes[0] });
  }
  return out;
}

function walkFiles(dir) {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...walkFiles(p));
    else if (e.isFile()) out.push(p);
  }
  return out;
}

function surfaceFiles() {
  const ui = walkFiles(path.join(repoRoot, 'web', 'ui'));
  const publicAssets = walkFiles(path.join(repoRoot, 'web', 'public'));
  const pages = walkFiles(path.join(repoRoot, 'internal', 'pages')).filter(
    (p) => p.endsWith('.go') && !p.endsWith('_test.go'),
  );
  return ui
    .concat(publicAssets, pages)
    .map((p) => path.relative(repoRoot, p).split(path.sep).join('/'))
    .sort();
}

function surfaceHash() {
  let lines = '';
  for (const rel of surfaceFiles()) {
    lines += `${sha256Hex(fs.readFileSync(path.join(repoRoot, rel)))}  ${rel}\n`;
  }
  return sha256Hex(Buffer.from(lines, 'utf8'));
}

function topicHash(locale, id) {
  let p = path.join(repoRoot, 'web', 'help', locale, `${id}.md`);
  if (!fs.existsSync(p)) p = path.join(repoRoot, 'web', 'help', 'en', `${id}.md`);
  return sha256Hex(fs.readFileSync(p));
}

function buildManifest() {
  const topics = {};
  for (const t of routedTopics()) {
    topics[t.id] = {};
    for (const locale of LOCALES) topics[t.id][locale] = topicHash(locale, t.id);
  }
  return {
    _comment:
      'Generated by `make docs-shots` (e2e/tests-docs/write-manifest.js); ' +
      'checked by scripts/ci/guard-docs-shots.sh. Do not edit by hand.',
    algorithm:
      'sha256; surface_sha256 = sha256 of concat of "<sha256(file)>  <relpath>\\n" ' +
      'for the sorted fileset (web/ui/** + non-test internal/pages/**.go); ' +
      'topic hashes = sha256 of the topic markdown (en fallback). ' +
      'Full spec in e2e/tests-docs/lib.js.',
    surface_sha256: surfaceHash(),
    topics,
  };
}

module.exports = { repoRoot, LOCALES, routedTopics, buildManifest };
