-- 053: real uniqueness for plugin_settings GLOBAL rows, closing the
-- scope_id-is-NULL gap (ut-docs#787).
--
-- plugin_settings' table-level UNIQUE(plugin_id, key, scope, scope_id) in
-- 001_init.sql is a no-op for scope='global' rows: scope_id is NULL for
-- them, and SQLite treats NULLs as distinct in a unique index, so two
-- global rows for the same key never conflict. ut-docs#785 closed the one
-- known race that exploited this; ut-docs#788 (migration 052, which
-- always runs before this one since migrations apply in ascending order)
-- repaired any pre-existing duplicate global rows -- so this migration
-- needs no dedupe step of its own. This is the schema-level backstop for
-- every writer, present and future, including the LAN-sync apply path
-- (sync_admin_repo.go's applyPluginSettings), which has no upsert-in-place
-- semantics of its own for plugin_settings.
--
-- Deliberately a PARTIAL index (WHERE scope = 'global'), not a general one
-- over all scopes. Register/user-scoped rows also store scope_id as NULL
-- today (see UpsertPluginSettingScoped's comment), so in principle the
-- same gap applies there too -- but neither scope has a realistic
-- concurrent writer (each is one till's own local state, per #785's own
-- review scope), and critically, no migration has ever deduped them the
-- way 052 dedupes global rows. A general (non-partial) version of this
-- index would make 053 itself FAIL TO APPLY on any till that happens to
-- already carry a pre-existing register/user duplicate -- turning a data-
-- integrity improvement into a startup-breaking migration for such a
-- till. Scoping to 'global' only avoids that risk entirely -- this is
-- slightly wider than 052's own repair predicate (052 only touches
-- scope='global' AND scope_id IS NULL rows; this index has no scope_id
-- clause), but nothing in this codebase ever writes a non-NULL scope_id
-- for a global row, so that gap is not known to be reachable today.
-- Widening to register/user is a separate follow-up if those scopes are
-- ever found to need it in practice.
CREATE UNIQUE INDEX IF NOT EXISTS ux_plugin_settings_global
    ON plugin_settings (plugin_id, key)
    WHERE scope = 'global';
